name: Generate Bitcoin Addresses

on:
  push:
    branches:
      - main

jobs:
  generate_addresses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.5" # Use the version of Python required by your script

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bitcoin address generator
        run: python address.py # Replace with the path to your Python script
